"""Added mailing table fix

Revision ID: 14167f3a94b1
Revises: 28605352905c
Create Date: 2023-04-17 17:34:53.066071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14167f3a94b1'
down_revision = '28605352905c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL_START', 'SHIFT', 'CLEANING', 'PROMOCODE', 'BONUS', 'REFUND', name='mailingtype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'type'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing')
    # ### end Alembic commands ###
