"""Added mailing table

Revision ID: 28605352905c
Revises: 
Create Date: 2023-04-17 17:33:14.503497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28605352905c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'manual_start', ['id'])
    op.create_unique_constraint(None, 'paid_manual_start', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paid_manual_start', type_='unique')
    op.drop_constraint(None, 'manual_start', type_='unique')
    # ### end Alembic commands ###
