"""fix

Revision ID: 4f420683a133
Revises: b9b674c718d0
Create Date: 2023-04-18 17:51:58.257192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f420683a133'
down_revision = 'b9b674c718d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL_START_ALERT', 'MANUAL_START', 'SHIFT', 'CLEANING', 'PROMOCODE', 'BONUS', 'REFUND', name='mailingtype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tg_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'type')
    )
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL_START_ALERT', 'MANUAL_START', 'SHIFT', 'CLEANING', 'PROMOCODE', 'BONUS', 'REFUND', name='mailingtype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'type')
    )
    op.create_unique_constraint(None, 'tg_group', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_group', type_='unique')
    op.drop_table('mailing')
    op.drop_table('group_mailing')
    # ### end Alembic commands ###
