"""mailing table another fix

Revision ID: eed3ce3a359f
Revises: 14167f3a94b1
Create Date: 2023-04-17 17:37:12.015788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed3ce3a359f'
down_revision = '14167f3a94b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mailing_type_key', 'mailing', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mailing_type_key', 'mailing', ['type'])
    # ### end Alembic commands ###
